[server] 
headless = true 
port = $PORT 
enableCORS = false 
enableXsrfProtection = false 
 
[theme] 
primaryColor = "#DA291C" 
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F2F6" 
textColor = "#262730" 
